# Generated by Django 5.0.6 on 2024-07-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_name', models.CharField(max_length=100)),
                ('A_pwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_id', models.IntegerField()),
                ('U_name', models.CharField(max_length=100)),
                ('U_pwd', models.CharField(max_length=100)),
                ('U_email', models.CharField(max_length=100)),
            ],
        ),
    ]
